version: "3.9"
services:
  logstash:
    image: logstash:8.10.2
    depends_on:
      - elastic
    environment:
      XPACK_MONITORING_ENABLED: "false"
      ES_HOST: "elastic:9200"
    ports:
      - "5044:5044"
    volumes:
      - ./deploy/logstash.conf:/config/logstash.conf:ro
    command: logstash -f /config/logstash.conf
    networks:
      - elk_default

  elastic:
    image: elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - ./deploy/esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: curl -s http://127.0.0.1:9200 > /dev/null || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - elk_default

  kibana:
    image: kibana:8.10.2
    ports:
      - "5601:5601"
    depends_on:
      elastic:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic:9200
    networks:
      - elk_default


networks:
  elk_default:
    driver: bridge