version: "3.3"

services:

  flask:
    build: .
    command: "gunicorn -w 2 main:app --bind 0.0.0.0:${FLASK_INTERNAL_PORT}"
    expose:
      - "${FLASK_INTERNAL_PORT}"
    restart: on-failure
    volumes:
      - ./.env:/app/src/.env
    env_file:
      - .env


  nginx:
    image: "nginx:1.25.3"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./data/html:/data/html:ro
    depends_on:
      - flask
    ports:
      - "80:80"