filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - /var/log/nginx/json-logs.json

  json:
    keys_under_root: true
    add_error_key: true

output.logstash:
  enabled: true
  hosts: ["logstash:5044"]